sudo: false
language: node_js
node_js:
- 'stable'
install:
- npm install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
script:
- npm run test
notifications:
  email:
    on_success: change
    on_failure: always
